
language: rust
cache: cargo

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

script:
  - cargo test
  - cargo test --features unwinder_unwind_rs --no-default-features
  - cargo run --example simple || true
  - cargo run --example simple --features unwinder_unwind_rs --no-default-features || true

env:
- RUST_BACKTRACE=pretty
