
language: rust
cache: cargo

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

script:
  - cargo test
  - cargo run --example simple || true
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    cargo test --features unwinder_unwind_rs --no-default-features;
    cargo run --example simple --features unwinder_unwind_rs --no-default-features || true;
    fi

env:
- RUST_BACKTRACE=pretty
